import {
  Award,
  BarChart3,
  DollarSign,
  FileText,
  MessageSquare,
  Settings,
  Shield,
  Target,
  Users,
} from 'lucide-react';
import {
  BUYER_REGISTER,
  CARGO,
  DOC_REQUEST,
  INFO,
  INVOICE,
  PRIVATE_INVOICE,
  PURCHASE_REG,
  REPORTS,
  WAREHOUSE,
} from '~/routes/constants';

export const dashboardItems = [
  {
    title: 'صدور فاکتور',
    subtitle: 'Hall Manager',
    icon: Settings,
    color: 'from-teal-400 to-teal-600',
    description: 'مدیریت و صدور فاکتورها',
    to: INVOICE,
  },
  {
    title: 'درخواست سنگ',
    subtitle: 'Document Request',
    icon: FileText,
    color: 'from-blue-400 to-blue-600',
    description: 'مدیریت اسناد و درخواست‌ها',
    to: DOC_REQUEST,
  },
  {
    title: 'ثبت خریدار',
    subtitle: 'Buyer Registration',
    icon: Users,
    color: 'from-purple-400 to-purple-600',
    description: 'ثبت و مدیریت خریداران',
    to: BUYER_REGISTER,
  },
  {
    title: 'رسید تحویل بار',
    subtitle: 'Cargo Tracking',
    icon: Target,
    color: 'from-green-400 to-green-600',
    description: 'پیگیری و رصد بارها',
    to: CARGO,
  },
  {
    title: 'ثبت خرید',
    subtitle: 'Purchase Registration',
    icon: Award,
    color: 'from-orange-400 to-orange-600',
    description: 'ثبت خریدها و معاملات',
    to: PURCHASE_REG,
  },
  {
    title: 'صورت حساب اشخاص',
    subtitle: 'Private Invoice',
    icon: DollarSign,
    color: 'from-red-400 to-red-600',
    description: 'مدیریت صورت حساب‌ها',
    to: PRIVATE_INVOICE,
  },
  {
    title: 'گزارشات',
    subtitle: 'Reports',
    icon: BarChart3,
    color: 'from-indigo-400 to-indigo-600',
    description: 'گزارش‌گیری و آمار',
    to: REPORTS,
  },
  {
    title: 'مشخصات شرکت/فروشنده',
    subtitle: 'Company/Seller Info',
    icon: Shield,
    color: 'from-emerald-400 to-emerald-600',
    description: 'اطلاعات شرکت و فروشنده',
    to: INFO,
  },
  {
    title: 'انبار سنگ',
    subtitle: 'Document Correction',
    icon: FileText,
    color: 'from-violet-400 to-violet-600',
    description: 'اصلاح و ویرایش انبار',
    to: WAREHOUSE,
  },
  {
    title: 'خروج',
    subtitle: 'Promotion',
    icon: MessageSquare,
    color: 'from-yellow-400 to-yellow-600',
    description: 'خروج از سیستم',
    to: '/',
  },
];
